### ISSUE TITLE
brew cu命令报错

### ISSUE THREAD

**Issue by ethuh** [HeminWon/CleanMyMac#1]
![CleanShot 2024-10-24 at 16 33 09@2x](https://github.com/user-attachments/assets/f174e3c0-bcd3-4bce-932c-f84a6731cfe3)

**Comment by HeminWon** [comment]
项目中使用了[homebrew-cask-upgrade](https://github.com/buo/homebrew-cask-upgrade) 若报错需要先安装
```shell
arch --arm64 brew tap buo/cask-upgrade
```
